### ISSUE TITLE
Deploy Build Failing on MS Azure

### ISSUE THREAD

**Issue by ovflowd** [ritterim/jekyll-azure-deploy#3]
Hi, i'm just newbie at Ruby and those things, i tried to deploy a Jekyll Website to my MS Azure Web App, but the build is failing and the Jekyll isn't being parsed.

The URI is https://uiotbeta.azurewebsites.net, and the repository: https://github.com/uiot/uiot.github.io/

Thanks!

**Comment by kendaleiv** [comment]
Is the deployment output showing any errors?

**Comment by ovflowd** [comment]
Yes. I will attach they.

**Comment by ovflowd** [comment]
I discovered a little type mistake of mine part in `deploy.cmd`

"%DEPLOYMENT_SOURCE%/_site" was "%DEPLOYMENT_SOURCE%s"

since i tried to remove the _site, (Ruby was saying that the folder doesn't exists)

Will try build it again.

**Comment by ovflowd** [comment]
Output log:

<pre>
Command: deploy.cmd
CALLING GET RUBY
D:\home\site\repository
Successfully installed bundler-1.13.6
Parsing documentation for bundler-1.13.6
Done installing documentation for bundler after 19 seconds
1 gem installed
Bundler install (not update)
Could not locate Gemfile or .bundle/ directory
D:\home\site\repository
Running Jekyll
Could not locate Gemfile or .bundle/ directory
Failed exitCode=10, command="getruby.cmd"
WE MADE IT
Handling Basic Web Site deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'getruby.cmd'
Finished successfully.
</pre>

Build sayd successfully on MS Azure, but Jekyll doesn't loaded. (http://uiotbeta.azurewebsites.net/)

**Comment by ovflowd** [comment]
Nevermind. Got it working.

**Comment by ovflowd** [comment]
Okay, build successful but web site still messed up.
http://betauiot.azurewebsites.net/.

**Comment by ovflowd** [comment]
Output log:

<pre>
Command: deploy.cmd
CALLING GET RUBY
No Ruby, need to get it
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  2 10.7M    2  320k    0     0   161k      0  0:01:07  0:00:01  0:01:06  369k
 35 10.7M   35 3855k    0     0  1321k      0  0:00:08  0:00:02  0:00:06 2137k
100 10.7M  100 10.7M    0     0  2960k      0  0:00:03  0:00:03 --:--:-- 4232k
START Unzipping Ruby
DONE Unzipping Ruby
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 10 42.2M   10 4612k    0     0  7315k      0  0:00:05 --:--:--  0:00:05 8355k
 31 42.2M   31 13.1M    0     0  8211k      0  0:00:05  0:00:01  0:00:04 8621k
 49 42.2M   49 20.7M    0     0  8064k      0  0:00:05  0:00:02  0:00:03 8311k
 67 42.2M   67 28.4M    0     0  8021k      0  0:00:05  0:00:03  0:00:02 8196k
 85 42.2M   85 36.1M    0     0  8007k      0  0:00:05  0:00:04  0:00:01 8144k
100 42.2M  100 42.2M    0     0  8044k      0  0:00:05  0:00:05 --:--:-- 8141k
START Unzipping DevKit
DONE Unzipping DevKit

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.
[INFO] Updating convenience notice gem override for 'D:/home/site/deployments/tools/r/ruby-2.3.1-x64-mingw32'
[INFO] Installing 'D:/home/site/deployments/tools/r/ruby-2.3.1-x64-mingw32/lib/ruby/site_ruby/devkit.rb'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  733k  100  733k    0     0  3332k      0 --:--:-- --:--:-- --:--:-- 3646k
Successfully installed rubygems-update-2.6.8
Parsing documentation for rubygems-update-2.6.8
Installing ri documentation for rubygems-update-2.6.8
Done installing documentation for rubygems-update after 102 seconds
1 gem installed
What's our new Rubygems version?
2.6.8
Removing update_rubygems
Successfully uninstalled rubygems-update-2.6.8
D:\home\site\repository
Successfully installed bundler-1.13.6
Parsing documentation for bundler-1.13.6
Installing ri documentation for bundler-1.13.6
Done installing documentation for bundler after 45 seconds
1 gem installed
Bundler install (not update!)
Could not locate Gemfile or .bundle/ directory
D:\home\site\repository
Running Jekyll
Could not locate Gemfile or .bundle/ directory
Failed exitCode=10, command="getruby.cmd"
WE MADE IT
Handling Basic Web Site deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: '.gitignore'
Copying file: 'favicon.ico'
Copying file: 'getruby.cmd'
Copying file: 'index.html'
Copying file: 'README.md'
Copying file: '_config.yml'
Copying file: '.idea\jsLibraryMappings.xml'
Copying file: '.idea\modules.xml'
Copying file: '.idea\uiot.github.io.iml'
Copying file: '.idea\vcs.xml'
Copying file: '.idea\dictionaries\santoro.xml'
Copying file: 'blog\atom.xml'
Copying file: 'blog\index.html'
Copying file: 'css\normalize.css'
Copying file: 'css\uiot.css'
Copying file: 'fonts\museosansrounded-100-webfont.eot'
Copying file: 'fonts\museosansrounded-100-webfont.woff'
Copying file: 'fonts\museosansrounded-1000-webfont.eot'
Copying file: 'fonts\museosansrounded-1000-webfont.woff'
Copying file: 'fonts\museosansrounded-300-webfont.eot'
Copying file: 'fonts\museosansrounded-300-webfont.woff'
Copying file: 'fonts\museosansrounded-500-webfont.eot'
Copying file: 'fonts\museosansrounded-500-webfont.woff'
Copying file: 'fonts\museosansrounded-700-webfont.eot'
Copying file: 'fonts\museosansrounded-700-webfont.woff'
Copying file: 'fonts\museosansrounded-900-webfont.eot'
Copying file: 'fonts\museosansrounded-900-webfont.woff'
Copying file: 'img\arrows.png'
Copying file: 'img\bolhas.png'
Copying file: 'img\chip.png'
Copying file: 'img\circuits.png'
Copying file: 'img\lilcircuits.png'
Copying file: 'img\map.gif'
Copying file: 'img\mountains.png'
Copying file: 'img\notebook.png'
Copying file: 'img\play-store.png'
Copying file: 'img\smart.png'
Copying file: 'img\uiot.svg'
Copying file: 'img\worlddotted.png'
Copying file: 'img\logos\bizagi.png'
Copying file: 'img\logos\devmind.png'
Copying file: 'img\logos\github.png'
Copying file: 'img\logos\google-launchpad.png'
Copying file: 'img\logos\ibm-gep.png'
Copying file: 'img\logos\jetbrains.png'
Copying file: 'img\logos\latitude.png'
Copying file: 'img\logos\malwarebytes.png'
Copying file: 'img\logos\microsoft-bizspark.png'
Omitting next output lines...
Finished successfully.
</pre>

**Comment by ovflowd** [comment]
I think the error is this:

<pre>
Could not locate Gemfile or .bundle/ directory
Failed exitCode=10, command="getruby.cmd"
</pre>

**Comment by khalidabuhakmeh** [comment]
I guess the obvious question is:

> Does your Jekyll directory have a `GemFile`?

https://github.com/ritterim/ritterim.github.io/blob/master/Gemfile

Here is ours for hosting our blog on GitHub pages, but yours may look different. :)

**Comment by khalidabuhakmeh** [comment]
Dude... that site is "messed up?" It looks amazing!

**Comment by ovflowd** [comment]
Thanks! It's because i tried to run local "jekyll build"
Will try to switch to non-local.

Can i delete the "_site" folder and changed in deploy.cmd to avoid using _site path?

**Comment by ovflowd** [comment]
But thanks for the Pull Request. Will try to figure it out.
I'm really newbie at Jekyll and Ruby hahaha.

**Comment by ovflowd** [comment]
Okay! Build succeeded.

By mistake changed from `_site/` to `/` and need have _site.

**Comment by ovflowd** [comment]
Here we go. Everything working.: https://betauiot.azurewebsites.net/

**Comment by ovflowd** [comment]
Ok, saw a bug: 
https://betauiot.azurewebsites.net/blog/2016/12/05/O-Tempo-do-Amanha vs https://uiot.github.io/blog/2016/12/05/O-Tempo-do-Amanha

What's happening?
Isn't MS Azure creating Symlinks?

Here is the `_config.yml` snippet:
`permalink: /blog/:year/:month/:day/:title`

Ah okay. Need put .html on the end.

**Comment by khalidabuhakmeh** [comment]
This is a `web.config` for a private `jekyll` site we are running. It includes a rewrite rule that removes the `.html` extensions. Also has an error handler called `/woops/` which you should change.

```xml

<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <httpErrors defaultPath="/woops/" defaultResponseMode="Redirect">
    </httpErrors>
    <modules runAllManagedModulesForAllRequests="true" />
    <rewrite>
      <rules>
        <rule name="RewriteHtml">
          <match url="^(.*)$" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REMOTE_PORT}" pattern=".*" />
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="{R:1}.html" />
        </rule>
      </rules>
    </rewrite>    
  </system.webServer>
</configuration>
```

**Comment by ovflowd** [comment]
Thanks @khalidabuhakmeh i Googled a little and already did it too.

But thanks anyways!!

**Comment by khalidabuhakmeh** [comment]
Looks like you got your deployment working :) Great job! 

I'll close this issue, but feel free to open another issue if you have more road blocks.
